[profile.default]
name = "BaseCard"
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"


[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
